version: "3"
services:
  postgresql:
    image: postgres:14-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432  
    volumes:
      - ./data/postgresql/docker:/var/lib/postgresql/data
      - ./data/postgresql/config/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./data/postgresql/config/users_seed.sql:/docker-entrypoint-initdb.d/users_seed.sql
      - ./data/postgresql/config/products_seed.sql:/docker-entrypoint-initdb.d/products_seed.sql
  
  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "maycon.carlete@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - 16543:80
    depends_on:
      - postgresql

  minio:
    user: 1000:1000
    image: minio/minio
    # restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio/docker:/data
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "123456789"
      MINIO_ADDRESS: ":9000"
      MINIO_CONSOLE_ADDRESS: ":9001"
    command: minio server /data